name: build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go ${{ matrix.node-version }}
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Run Setup
        run: make setup
      
      - name: Run Tests
        run: make test

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          skip-go-installation: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}